version: 0.1

phases:
  build:
    commands:
      - echo Nothing to do yet
artifacts:
  files:
    - index.html
    - babel.html
    - favicon.ico
    - images/2017-07 Skills CV - LSA-DO.pdf
    - styles/main.css
    - styles/portfolio.css
    - images/*
