version: 0.1

phases:
  build:
    commands:
      - npm install
      - npm run webpack
artifacts:
  files:
    - ./*.html
    - favicon.ico
    - images/2017-10_Skills_CV-LSA-DO.pdf
    - styles/*.css
    - images/*
    - dist/bundle.js
