version: 0.1

phases:
  pre_build:
    commands:
      - npm install
      - npm test
  build:
    commands:
      - npm run webpack
artifacts:
  files:
    - ./*.html
    - favicon.ico
    - styles/*.css
    - images/*
    - dist/bundle.js
    - data/*.json
    - demos/*.html
